//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueTracker.Locale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IssueStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IssueStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IssueTracker.Locale.Issue.IssueStrings", typeof(IssueStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to issue.
        /// </summary>
        public static string BackToIssue {
            get {
                return ResourceManager.GetString("BackToIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change state to: .
        /// </summary>
        public static string ChangeState {
            get {
                return ResourceManager.GetString("ChangeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have attempted to create an issue at the project, for which you are not among its users..
        /// </summary>
        public static string ErrorMessageInvalidProjectCreate {
            get {
                return ResourceManager.GetString("ErrorMessageInvalidProjectCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have attempted to move an issue to the project, for which you are not among its users..
        /// </summary>
        public static string ErrorMessageInvalidProjectEdit {
            get {
                return ResourceManager.GetString("ErrorMessageInvalidProjectEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no initial state. The issue couldn&apos;t be created..
        /// </summary>
        public static string ErrorMessageNoIniState {
            get {
                return ResourceManager.GetString("ErrorMessageNoIniState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignee.
        /// </summary>
        public static string IssueAssigneeId {
            get {
                return ResourceManager.GetString("IssueAssigneeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unassigned.
        /// </summary>
        public static string IssueAssigneeUnassigned {
            get {
                return ResourceManager.GetString("IssueAssigneeUnassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string IssueCreated {
            get {
                return ResourceManager.GetString("IssueCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue description.
        /// </summary>
        public static string IssueDescription {
            get {
                return ResourceManager.GetString("IssueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string IssueProjectId {
            get {
                return ResourceManager.GetString("IssueProjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporter.
        /// </summary>
        public static string IssueReporterId {
            get {
                return ResourceManager.GetString("IssueReporterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string IssueState {
            get {
                return ResourceManager.GetString("IssueState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string IssueTitle {
            get {
                return ResourceManager.GetString("IssueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string IssueType {
            get {
                return ResourceManager.GetString("IssueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug.
        /// </summary>
        public static string IssueTypeBug {
            get {
                return ResourceManager.GetString("IssueTypeBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string IssueTypeQuestion {
            get {
                return ResourceManager.GetString("IssueTypeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string IssueTypeTask {
            get {
                return ResourceManager.GetString("IssueTypeTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No issue found..
        /// </summary>
        public static string ListNoResult {
            get {
                return ResourceManager.GetString("ListNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SearchNamePlaceholder {
            get {
                return ResourceManager.GetString("SearchNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Select assignee -.
        /// </summary>
        public static string SelectAssigneeDefault {
            get {
                return ResourceManager.GetString("SelectAssigneeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Select project -.
        /// </summary>
        public static string SelectProjectDefault {
            get {
                return ResourceManager.GetString("SelectProjectDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Select reporter -.
        /// </summary>
        public static string SelectReporterDefault {
            get {
                return ResourceManager.GetString("SelectReporterDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Select state -.
        /// </summary>
        public static string SelectStateDefault {
            get {
                return ResourceManager.GetString("SelectStateDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Select type -.
        /// </summary>
        public static string SelectTypeDefault {
            get {
                return ResourceManager.GetString("SelectTypeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned to me.
        /// </summary>
        public static string TabAssignedToMe {
            get {
                return ResourceManager.GetString("TabAssignedToMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by me.
        /// </summary>
        public static string TabCreatedByMe {
            get {
                return ResourceManager.GetString("TabCreatedByMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reported by me.
        /// </summary>
        public static string TabReportedByMe {
            get {
                return ResourceManager.GetString("TabReportedByMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new issue.
        /// </summary>
        public static string TitleCreate {
            get {
                return ResourceManager.GetString("TitleCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue {0}.
        /// </summary>
        public static string TitleDetails {
            get {
                return ResourceManager.GetString("TitleDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit issue {0}.
        /// </summary>
        public static string TitleEdit {
            get {
                return ResourceManager.GetString("TitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues.
        /// </summary>
        public static string TitleIndex {
            get {
                return ResourceManager.GetString("TitleIndex", resourceCulture);
            }
        }
    }
}
